package("devbench-api")
set_kind("library", { headeronly = true })
set_homepage("https://github.com/gabriel-andreescu/modorganizer-dev_bench")
set_description("DevBench plugin API")
set_license("MIT")
add_urls("https://github.com/gabriel-andreescu/modorganizer-dev_bench.git")
add_versions("0.1.0", "v0.1.0")
on_install(function(package)
    os.cp("include/DevBenchAPI.h", package:installdir("include"))
    os.cp("include/DevBenchQt.h", package:installdir("include"))
    os.cp("include/DevBenchAPI.cpp", package:installdir("share"))
    os.cp("include/DevBenchAPI.LICENSE.txt", package:installdir("share"))
end)
