package("mo2-libbsarch")
set_homepage("https://github.com/ModOrganizer2/libbsarch")
set_description("MO2's BSArchive library and C++ bindings")
set_license("MIT")
add_urls("https://github.com/ModOrganizer2/libbsarch/releases/download/$(version)/libbsarch_$(version).7z")
add_versions("0.1.2", "dc62f8d226392921818cc921beabbb976f8be3cd62788678d8c966879c64e861")
add_deps("mo2-dds-header")
add_links("libbsarch_OOP", "libbsarch")
on_install("windows|x64", function(package)
    -- MO2 ships libbsarch.dll.
    os.cp("include/*", package:installdir("include"))
    os.cp("lib/libbsarch.lib", package:installdir("lib"))
    os.cp("lib/libbsarch_OOP.lib", package:installdir("lib"))
end)
